name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [ push ]
jobs:
  Explore-GitHub-Actions:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          # install depends
          pip install -r requirements.txt
          # linting
          ruff check
          ruff format --check
          # start databases
          cd Async_API_sprint_1
          docker compose up -d postgres elastic-search redis
          sleep 30
          # init indexes
          bash scripts/init_indexes_es/curl_movies_index.bash
          bash scripts/init_indexes_es/curl_genres_index.bash
          bash scripts/init_indexes_es/curl_persons_index.bash
          # migrate data to elastic
          docker compose up -d etl-app
          sleep 10
          docker compose down etl-app
          cd ..
          # testing
          pytest -sv
          coverage run -m pytest
          coverage report -m
          # stop containers
          docker compose down     

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
